package com.nguonchhay.msgshareapp.models

data class Hobby(var title: String)

object HobbiesSupplier {
    val hobbies = listOf(
        Hobby("Swimming"),
        Hobby("Reading"),
        Hobby("Walking"),
        Hobby("Sleeping"),
        Hobby("Gaming"),
        Hobby("Programming"),
        Hobby("Talking"),
        Hobby("Swimming"),
        Hobby("Reading"),
        Hobby("Walking"),
        Hobby("Sleeping"),
        Hobby("Gaming"),
        Hobby("Programming"),
        Hobby("Talking"),
        Hobby("Swimming"),
        Hobby("Reading"),
        Hobby("Walking"),
        Hobby("Sleeping"),
        Hobby("Gaming"),
        Hobby("Programming"),
        Hobby("Talking"),
        Hobby("Swimming"),
        Hobby("Reading"),
        Hobby("Walking"),
        Hobby("Sleeping"),
        Hobby("Gaming"),
        Hobby("Programming"),
        Hobby("Talking"),
        Hobby("Swimming"),
        Hobby("Reading"),
        Hobby("Walking"),
        Hobby("Sleeping"),
        Hobby("Gaming"),
        Hobby("Programming"),
        Hobby("Talking"),
        Hobby("Swimming"),
        Hobby("Reading"),
        Hobby("Walking"),
        Hobby("Sleeping"),
        Hobby("Gaming"),
        Hobby("Programming"),
        Hobby("Talking")
    )
}